/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface IdPhotoBody3
 */
export interface IdPhotoBody3 {
  /**
   * The photo to use.
   *
   * @type {Blob}
   * @memberof IdPhotoBody3
   */
  photo: Blob;
}
