/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ImageListInner
 */
export interface ImageListInner {
  /**
   * @type {string}
   * @memberof ImageListInner
   */
  href?: string;

  /**
   * @type {string}
   * @memberof ImageListInner
   */
  mime?: string;

  /**
   * @type {string}
   * @memberof ImageListInner
   */
  hash?: string;

  /**
   * @type {string}
   * @memberof ImageListInner
   */
  filename?: string;

  /**
   * @type {number}
   * @memberof ImageListInner
   */
  width?: number;

  /**
   * @type {number}
   * @memberof ImageListInner
   */
  height?: number;
}
