/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Banner } from "./banner";
import { Contest } from "./contest";
import { ImageList } from "./image-list";

/**
 *
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 extends Contest {
  /**
   * @type {ImageList}
   * @memberof InlineResponse2001
   */
  banner?: ImageList;
}
