/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
  /**
   * The ID of the imported problem
   *
   * @type {number}
   * @memberof InlineResponse2007
   */
  problem_id?: number;

  /**
   * @type {Array<string>}
   * @memberof InlineResponse2007
   */
  messages?: Array<string>;
}
