/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Submission
 */
export interface Submission {
  /**
   * @type {string}
   * @memberof Submission
   */
  language_id?: string;

  /**
   * @type {string}
   * @memberof Submission
   */
  time?: string;

  /**
   * @type {string}
   * @memberof Submission
   */
  contest_time?: string;

  /**
   * @type {string}
   * @memberof Submission
   */
  team_id?: string;

  /**
   * @type {string}
   * @memberof Submission
   */
  problem_id?: string;

  /**
   * @type {string}
   * @memberof Submission
   */
  id?: string;

  /**
   * @type {string}
   * @memberof Submission
   */
  external_id?: string | null;

  /**
   * @type {string}
   * @memberof Submission
   */
  entry_point?: string | null;
}
