/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * @type {Date}
   * @memberof User
   */
  last_login_time?: Date | null;

  /**
   * @type {Date}
   * @memberof User
   */
  last_api_login_time?: Date | null;

  /**
   * @type {Date}
   * @memberof User
   */
  first_login_time?: Date | null;

  /**
   * @type {string}
   * @memberof User
   */
  team?: string | null;

  /**
   * @type {string}
   * @memberof User
   */
  team_id?: string | null;

  /**
   * @type {Array<string>}
   * @memberof User
   */
  roles?: Array<string>;

  /**
   * @type {string}
   * @memberof User
   */
  type?: string | null;

  /**
   * @type {string}
   * @memberof User
   */
  id?: string;

  /**
   * @type {string}
   * @memberof User
   */
  username?: string;

  /**
   * @type {string}
   * @memberof User
   */
  name?: string;

  /**
   * @type {string}
   * @memberof User
   */
  email?: string | null;

  /**
   * @type {string}
   * @memberof User
   */
  last_ip?: string | null;

  /**
   * @type {string}
   * @memberof User
   */
  ip?: string | null;

  /**
   * @type {boolean}
   * @memberof User
   */
  enabled?: boolean;
}
