services:
  webapp:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./webapp:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    user: node
    command: sh -c "npm install && npm run dev"
