services:
  # Database
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  judgehost:
    image: tommyjqliu/judgehost:latest
    privileged: true
    restart: always 
    environment:
      - JUDGEDAEMON_PASSWORD=yourpassword
      - JUDGEDAEMON_READ_ONLY_PASSWORD=yourreadonlypassword
      - DOMSERVER_BASEURL=http://webapp:3000/
      - JUDGEDAEMON_NAME=judgehost
    depends_on:
      - rabbitmq
    # deploy:
    #   mode: replicated
    #   replicas: 2

  webapp:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
      - production.env
    ports:
      - "3000:3000"
    user: node
    command: npm run dev
    
  problemtools:
    image: tommyjqliu/problemtools-web:latest
    ports:
      - "5000:5000"
  
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - /etc/letsencrypt/live/uwajudge.tommydev.net/fullchain.pem:/etc/fullchain.pem
  #     - /etc/letsencrypt/live/uwajudge.tommydev.net/privkey.pem:/etc/privkey.pem
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   profiles:
  #     - prod 
  #   depends_on:
  #     - uwajudge

configs:
  pgpass:
    content: postgres:5432:*:${POSTGRES_USER}:${POSTGRES_PASSWORD}
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "Postgres",
        "Host": "postgres",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "${POSTGRES_USER}",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}