services:
  # Database
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "5050:80"
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  judgehost:
    image: test-judgehost-inject-build:latest
    privileged: true
    restart: always 
    environment:
      - JUDGEDAEMON_PASSWORD=yourpassword
      - JUDGEDAEMON_READ_ONLY_PASSWORD=yourreadonlypassword
      - DOMSERVER_BASEURL=http://webapp:3000/
      - JUDGEDAEMON_NAME=judgehost
    depends_on:
      - rabbitmq
  
  # problemtools:
  #   image: tommyjqliu/problemtools-web:latest
  #   ports:
  #     - "5000:5000"
  
  webapp:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
      - production.env
    ports:
      - "3000:3000"
    command: npm run dev
  
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - /etc/letsencrypt/live/uwajudge.tommydev.net/fullchain.pem:/etc/fullchain.pem
  #     - /etc/letsencrypt/live/uwajudge.tommydev.net/privkey.pem:/etc/privkey.pem
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   profiles:
  #     - prod 
  #   depends_on:
  #     - uwajudge
  

