services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  judgehost:
    image: test-judgehost-inject-build:latest
    privileged: true
    environment:
      - JUDGEDAEMON_PASSWORD=yourpassword
      - JUDGEDAEMON_READ_ONLY_PASSWORD=yourreadonlypassword
      - JUDGEDAEMON_MASTER=domserver
      - JUDGEDAEMON_NAME=judgehost
    depends_on:
      - rabbitmq
