/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Award
 */
export interface Award {

    /**
     * @type {string}
     * @memberof Award
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Award
     */
    citation?: string;

    /**
     * @type {Array<string>}
     * @memberof Award
     */
    teamIds?: Array<string>;
}
