/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import {
    Apiv4contestscidsubmissionsFiles,
} from ".";

/**
 * 
 *
 * @export
 * @interface CidSubmissionsBody1
 */
export interface CidSubmissionsBody1 {

    /**
     * The problem ID to submit a solution for
     *
     * @type {string}
     * @memberof CidSubmissionsBody1
     */
    problem_id: string;

    /**
     * The language to submit a solution in
     *
     * @type {string}
     * @memberof CidSubmissionsBody1
     */
    language_id: string;

    /**
     * The team to submit a solution for. Only used when adding a submission as admin
     *
     * @type {string}
     * @memberof CidSubmissionsBody1
     */
    team_id?: string;

    /**
     * The time to use for the submission. Only used when adding a submission as admin
     *
     * @type {Date}
     * @memberof CidSubmissionsBody1
     */
    time?: Date;

    /**
     * The ID to use for the submission. Only used when adding a submission as admin and only allowed with PUT
     *
     * @type {string}
     * @memberof CidSubmissionsBody1
     */
    id?: string;

    /**
     * The base64 encoded ZIP file to submit
     *
     * @type {Array<Apiv4contestscidsubmissionsFiles>}
     * @memberof CidSubmissionsBody1
     */
    files: Array<Apiv4contestscidsubmissionsFiles>;

    /**
     * The entry point for the submission. Required for languages requiring an entry point
     *
     * @type {string}
     * @memberof CidSubmissionsBody1
     */
    entry_point?: string;
}
