/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface HostnameJudgeTaskIdBody
 */
export interface HostnameJudgeTaskIdBody {

    /**
     * The result of the run
     *
     * @type {string}
     * @memberof HostnameJudgeTaskIdBody
     */
    runresult: string;

    /**
     * The runtime of the run
     *
     * @type {number}
     * @memberof HostnameJudgeTaskIdBody
     */
    runtime: number;

    /**
     * The (base64-encoded) output of the run
     *
     * @type {string}
     * @memberof HostnameJudgeTaskIdBody
     */
    output_run: string;

    /**
     * The (base64-encoded) output diff of the run
     *
     * @type {string}
     * @memberof HostnameJudgeTaskIdBody
     */
    output_diff: string;

    /**
     * The (base64-encoded) error output of the run
     *
     * @type {string}
     * @memberof HostnameJudgeTaskIdBody
     */
    output_error: string;

    /**
     * The (base64-encoded) system output of the run
     *
     * @type {string}
     * @memberof HostnameJudgeTaskIdBody
     */
    output_system: string;

    /**
     * The (base64-encoded) metadata
     *
     * @type {string}
     * @memberof HostnameJudgeTaskIdBody
     */
    metadata?: string;
}
