/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JudgementExtraFields } from './judgement-extra-fields';
import { Judging } from './judging';
import {
    JudgementExtraFields,Judging,
} from ".";

/**
 * 
 *
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 extends Judging {

    /**
     * @type {string}
     * @memberof InlineResponse2009
     */
    judgementTypeId?: string | null;

    /**
     * @type {string}
     * @memberof InlineResponse2009
     */
    judgehost?: string;

    /**
     * @type {number}
     * @memberof InlineResponse2009
     */
    maxRunTime?: number | null;
}
