/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface JudgingRun
 */
export interface JudgingRun {

    /**
     * @type {number}
     * @memberof JudgingRun
     */
    runTime?: number;

    /**
     * @type {string}
     * @memberof JudgingRun
     */
    time?: string;

    /**
     * @type {string}
     * @memberof JudgingRun
     */
    contestTime?: string;

    /**
     * @type {string}
     * @memberof JudgingRun
     */
    judgementId?: string;

    /**
     * @type {number}
     * @memberof JudgingRun
     */
    ordinal?: number;

    /**
     * @type {string}
     * @memberof JudgingRun
     */
    id?: string;
}
