/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface Language
 */
export interface Language {

    /**
     * @type {string}
     * @memberof Language
     */
    compileExecutableHash?: string | null;

    /**
     * @type {string}
     * @memberof Language
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Language
     */
    name: string;

    /**
     * @type {Array<string>}
     * @memberof Language
     */
    extensions: Array<string>;

    /**
     * @type {boolean}
     * @memberof Language
     */
    filterCompilerFiles?: boolean;

    /**
     * @type {boolean}
     * @memberof Language
     */
    allowJudge?: boolean;

    /**
     * @type {number}
     * @memberof Language
     */
    timeFactor: number;

    /**
     * @type {boolean}
     * @memberof Language
     */
    entryPointRequired?: boolean;

    /**
     * @type {string}
     * @memberof Language
     */
    entryPointName?: string | null;
}
