/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ContestState } from './contest-state';
import { ScoreboardRows } from './scoreboard-rows';
import {
    ContestState,ScoreboardRows,
} from ".";

/**
 * 
 *
 * @export
 * @interface Scoreboard
 */
export interface Scoreboard {

    /**
     * @type {string}
     * @memberof Scoreboard
     */
    eventId?: string;

    /**
     * @type {string}
     * @memberof Scoreboard
     */
    time?: string;

    /**
     * @type {string}
     * @memberof Scoreboard
     */
    contestTime?: string;

    /**
     * @type {ContestState}
     * @memberof Scoreboard
     */
    state?: ContestState;

    /**
     * @type {Array<ScoreboardRows>}
     * @memberof Scoreboard
     */
    rows?: Array<ScoreboardRows>;
}
