/* tslint:disable */
/* eslint-disable */
/**
 * DOMjudge
 * DOMjudge API v4
 *
 * OpenAPI spec version: 8.2.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface TeamCategory
 */
export interface TeamCategory {

    /**
     * @type {boolean}
     * @memberof TeamCategory
     */
    hidden?: boolean;

    /**
     * @type {string}
     * @memberof TeamCategory
     */
    id?: string;

    /**
     * @type {string}
     * @memberof TeamCategory
     */
    icpc_id?: string | null;

    /**
     * @type {string}
     * @memberof TeamCategory
     */
    name: string;

    /**
     * @type {number}
     * @memberof TeamCategory
     */
    sortorder?: number;

    /**
     * @type {string}
     * @memberof TeamCategory
     */
    color?: string | null;
}
